name: Deploy To Google Play

on:
  push:
    branches: [master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  distribute:
    name: Distribute APK to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app-java/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Assemble Release APK
        run: ./gradlew assembleRelease

      - name: Use Debug Keystore (Test Signing)
        run: |
          echo "storePassword=android" > keystore.properties
          echo "keyPassword=android" >> keystore.properties
          echo "keyAlias=androiddebugkey" >> keystore.properties
          echo "storeFile=$HOME/.android/debug.keystore" >> keystore.properties

      - name: Sign APK with Debug Keystore
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ""  # Kosongkan karena pakai debug keystore
          keyStorePassword: "android"
          alias: "androiddebugkey"
          keyPassword: "android"

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy APK to Google Play (Internal Testing)
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.startapp.demo.java
          releaseFiles: app-java/build/outputs/apk/release/app-release.apk
          track: 'internal'
          status: 'completed'
          whatsNewDirectory: whatsNew/
